exclude: ["CNAME", "README.md", "default.nix"]
permalink: /meetups/:title/

# content-related settings
cfp-url: https://docs.google.com/forms/d/1BFOO1Q6U1V0Nns2zsFRWphHA3_3T0BimKbhdjkgBxCY
meetup-url: https://www.meetup.com/Hack-Tell-Singapore/
engineers-sg-url: https://engineers.sg/organization/sg-hack-tell--184

next-meetup:
  enabled: true
  title: Hack and Tell - July 2018 Edition!
  url: https://www.meetup.com/Hack-Tell-Singapore/events/251397442/
  date: 5 July 2018
